apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-sep26-2v 
  janus-idp.io/tekton: codegen-sep26-2v
  backstage.io/kubernetes-id: codegen-sep26-2v
  backstage.io/kubernetes-namespace: codegen-sep26-2v 
  app.kubernetes.io/part-of: codegen-sep26-2v
resources: 
- application-dev.yaml