apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-codegen-sep26-2v-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-codegen-sep26-2v-gitops
    spec:  
      serviceAccountName: codegen-sep26-2v-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=codegen-sep26-2v-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/codegen-sep26-2v-notebook -- git clone https://github.com/redhat-appstudio-mjf/codegen-sep26-2v
      restartPolicy: Never