kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen-sep26-2v-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: codegen-sep26-2v-dsp-job
    namespace: codegen-sep26-2v
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen-sep26-2v-imagestream-job-role
