apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: codegen-sep26-2v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  codegen-sep26-2v
    app.kubernetes.io/part-of: codegen-sep26-2v  
  name: codegen-sep26-2v
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  codegen-sep26-2v 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  codegen-sep26-2v
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: codegen-sep26-2v-model-config
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
