apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-sep26-2v
  janus-idp.io/tekton: codegen-sep26-2v
  backstage.io/kubernetes-id: codegen-sep26-2v
  backstage.io/kubernetes-namespace: codegen-sep26-2v 
  app.kubernetes.io/part-of: codegen-sep26-2v
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
